name: my_diary
description: My Diary

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^6.0.6
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.4.1
  uuid: ^3.0.6
  table_calendar: ^3.0.6
  intl: ^0.17.0
  provider: ^6.0.3
  mockito: 5.2.0
  build_runner: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/google_icon.png

  generate: true
flutter_intl:
  enabled: true